use v6;
#  -- DO NOT EDIT --
# generated by: t/build.t 

class CSS::Aural::Spec::Actions {
    method expr-cue-after($/) { make $.list($/) }
    method expr-cue-before($/) { make $.list($/) }
    method generic-voice($/) { make $.node($/).pairs[0] }
    method specific-voice($/) { make $.node($/).pairs[0] }
}
