use v6;
#  -- DO NOT EDIT --
# generated by: t/build.t 

grammar CSS::Aural::Spec::Grammar {
    #| azimuth: <angle> | [[ left-side | far-left | left | center-left | center | center-right | right | far-right | right-side ] || behind ] | leftwards | rightwards
    rule decl:sym<azimuth> {:i (azimuth) ':'  [ <expr=.expr-azimuth> || <usage(&?ROUTINE.WHY)> ] }
    rule expr-azimuth {:i [ <angle> | [ [:my @*SEEN; [ [ left\-side | far\-left | left | center\-left | center | center\-right | right | far\-right | right\-side ] & <keyw> ] <!seen(0)> | behind & <keyw> <!seen(1)> ]+ ] | [ leftwards | rightwards ] & <keyw> ] }
    #| cue-after: <uri> | none
    rule decl:sym<cue-after> {:i (cue\-after) ':'  [ <expr=.expr-cue-after> || <usage(&?ROUTINE.WHY)> ] }
    rule expr-cue-after {:i [ <uri> | none & <keyw> ] }
    #| cue-before: <uri> | none
    rule decl:sym<cue-before> {:i (cue\-before) ':'  [ <expr=.expr-cue-before> || <usage(&?ROUTINE.WHY)> ] }
    rule expr-cue-before {:i [ <uri> | none & <keyw> ] }
    #| cue: [ 'cue-before' || 'cue-after' ]
    rule decl:sym<cue> {:i (cue) ':'  [ <expr=.expr-cue> || <usage(&?ROUTINE.WHY)> ] }
    rule expr-cue {:i [ [:my @*SEEN; <expr-cue-before> <!seen(0)> | <expr-cue-after> <!seen(1)> ]+ ] }
    #| elevation: <angle> | below | level | above | higher | lower
    rule decl:sym<elevation> {:i (elevation) ':'  [ <expr=.expr-elevation> || <usage(&?ROUTINE.WHY)> ] }
    rule expr-elevation {:i [ <angle> | [ below | level | above | higher | lower ] & <keyw> ] }
    #| pause: [ [<time> | <percentage>]{1,2} ]
    rule decl:sym<pause> {:i (pause) ':'  [ <expr=.expr-pause> || <usage(&?ROUTINE.WHY)> ] }
    rule expr-pause {:i [ [ [ <time> | <percentage> ] ]**1..2 ] }
    #| pause-after: <time> | <percentage>
    rule decl:sym<pause-after> {:i (pause\-after) ':'  [ <expr=.expr-pause-after> || <usage(&?ROUTINE.WHY)> ] }
    rule expr-pause-after {:i [ <time> | <percentage> ] }
    #| pause-before: <time> | <percentage>
    rule decl:sym<pause-before> {:i (pause\-before) ':'  [ <expr=.expr-pause-before> || <usage(&?ROUTINE.WHY)> ] }
    rule expr-pause-before {:i [ <time> | <percentage> ] }
    #| pitch-range: <number>
    rule decl:sym<pitch-range> {:i (pitch\-range) ':'  [ <expr=.expr-pitch-range> || <usage(&?ROUTINE.WHY)> ] }
    rule expr-pitch-range {:i <number> }
    #| pitch: <frequency> | x-low | low | medium | high | x-high
    rule decl:sym<pitch> {:i (pitch) ':'  [ <expr=.expr-pitch> || <usage(&?ROUTINE.WHY)> ] }
    rule expr-pitch {:i [ <frequency> | [ x\-low | low | medium | high | x\-high ] & <keyw> ] }
    #| play-during: <uri> [ mix || repeat ]? | auto | none
    rule decl:sym<play-during> {:i (play\-during) ':'  [ <expr=.expr-play-during> || <usage(&?ROUTINE.WHY)> ] }
    rule expr-play-during {:i [ <uri> [ [:my @*SEEN; mix & <keyw> <!seen(0)> | repeat & <keyw> <!seen(1)> ]+ ]? | [ auto | none ] & <keyw> ] }
    #| richness: <number>
    rule decl:sym<richness> {:i (richness) ':'  [ <expr=.expr-richness> || <usage(&?ROUTINE.WHY)> ] }
    rule expr-richness {:i <number> }
    #| speak: normal | none | spell-out
    rule decl:sym<speak> {:i (speak) ':'  [ <expr=.expr-speak> || <usage(&?ROUTINE.WHY)> ] }
    rule expr-speak {:i [ normal | none | spell\-out ] & <keyw> }
    #| speak-header: once | always
    rule decl:sym<speak-header> {:i (speak\-header) ':'  [ <expr=.expr-speak-header> || <usage(&?ROUTINE.WHY)> ] }
    rule expr-speak-header {:i [ once | always ] & <keyw> }
    #| speak-numeral: digits | continuous
    rule decl:sym<speak-numeral> {:i (speak\-numeral) ':'  [ <expr=.expr-speak-numeral> || <usage(&?ROUTINE.WHY)> ] }
    rule expr-speak-numeral {:i [ digits | continuous ] & <keyw> }
    #| speak-punctuation: code | none
    rule decl:sym<speak-punctuation> {:i (speak\-punctuation) ':'  [ <expr=.expr-speak-punctuation> || <usage(&?ROUTINE.WHY)> ] }
    rule expr-speak-punctuation {:i [ code | none ] & <keyw> }
    #| speech-rate: <number> | x-slow | slow | medium | fast | x-fast | faster | slower
    rule decl:sym<speech-rate> {:i (speech\-rate) ':'  [ <expr=.expr-speech-rate> || <usage(&?ROUTINE.WHY)> ] }
    rule expr-speech-rate {:i [ <number> | [ x\-slow | slow | medium | fast | x\-fast | faster | slower ] & <keyw> ] }
    #| stress: <number>
    rule decl:sym<stress> {:i (stress) ':'  [ <expr=.expr-stress> || <usage(&?ROUTINE.WHY)> ] }
    rule expr-stress {:i <number> }
    #| voice-family: [<specific-voice> | <generic-voice> ]#
    rule decl:sym<voice-family> {:i (voice\-family) ':'  [ <expr=.expr-voice-family> || <usage(&?ROUTINE.WHY)> ] }
    rule expr-voice-family {:i [ [ <specific-voice> | <generic-voice> ] ] +% ',' }
    #| volume: <number> | <percentage> | silent | x-soft | soft | medium | loud | x-loud
    rule decl:sym<volume> {:i (volume) ':'  [ <expr=.expr-volume> || <usage(&?ROUTINE.WHY)> ] }
    rule expr-volume {:i [ <number> | <percentage> | [ silent | x\-soft | soft | medium | loud | x\-loud ] & <keyw> ] }
}
