use v6;
#  -- DO NOT EDIT --
# generated by: t/build.t

class Test::CSS::Aural::Spec::Actions {
    method expr-cue-after($/) { make $.build.list($/) }
    method expr-cue-before($/) { make $.build.list($/) }
    method generic-voice($/) { make $.build.rule($/) }
    method specific-voice($/) { make $.build.rule($/) }
}
